Fail CI when changed/new git files are detected

diff --git a/.github/workflows/nightly_deps_check.yml b/.github/workflows/nightly_deps_check.yml
--- a/.github/workflows/nightly_deps_check.yml
+++ b/.github/workflows/nightly_deps_check.yml
@@ -70,6 +70,15 @@ jobs:
       run: cargo hack --feature-powerset clippy --all-targets --locked ${{ matrix.cargo_profile }} -- -D warnings
     - name: Ensure that tests pass under every possible combination of features
       run: cargo hack --feature-powerset test ${{ matrix.cargo_profile }}
+    - name: Ensure that tests did not create or modify any files that arent .gitignore'd
+      # This is important because we are checking in the Cargo.lock file.
+      # We want to fail CI if the Cargo.toml changed without including the corresponding Cargo.lock changes.
+      # Its also just generally nice to ensure your tests dont leave around unexpected files.
+      run: |
+        if [ -n "$(git status --porcelain)" ]; then
+          git status
+          exit 1
+        fi
     - uses: JasonEtco/create-an-issue@v2
       if: ${{ failure() }}
       env:
